//
// ConnectionsV2Test.cs
//
// This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace ConnectionsV2
{
	/// <summary>
	/// Summary description for ConnectionsV2Test.
	/// </summary>
	class ConnectionsV2Test
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   ConnectionsV2.ConnectionsV22 doc = ConnectionsV2.ConnectionsV22.CreateDocument();			
			//   ConnectionsV2.UserNameType root = doc.UserName.Append();
			//   ...
			//   doc.SaveToFile("ConnectionsV21.xml", true);
			//
			// Example code to load and save a structure:
			//   ConnectionsV2.ConnectionsV22 doc = ConnectionsV2.ConnectionsV22.LoadFromFile("ConnectionsV21.xml");
			//   ConnectionsV2.UserNameType root = doc.UserName.First;
			//   ...
			//   doc.SaveToFile("ConnectionsV21.xml", true);

		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("ConnectionsV2 Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
