//
// multiTable2oneXML_spyTest.cs
//
// This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace multiTable2oneXML_spy
{
	/// <summary>
	/// Summary description for multiTable2oneXML_spyTest.
	/// </summary>
	class multiTable2oneXML_spyTest
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   multiTable2oneXML_spy.multiTable2oneXML_spy2 doc = multiTable2oneXML_spy.multiTable2oneXML_spy2.CreateDocument();			
			//   multiTable2oneXML_spy.StreamNodesType root = doc.StreamNodes.Append();
			//   ...
			//   doc.SaveToFile("multiTable2oneXML_spy1.xml", true);
			//
			// Example code to load and save a structure:
			//   multiTable2oneXML_spy.multiTable2oneXML_spy2 doc = multiTable2oneXML_spy.multiTable2oneXML_spy2.LoadFromFile("multiTable2oneXML_spy1.xml");
			//   multiTable2oneXML_spy.StreamNodesType root = doc.StreamNodes.First;
			//   ...
			//   doc.SaveToFile("multiTable2oneXML_spy1.xml", true);

		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("multiTable2oneXML_spy Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
