//
// Web_ConfigTest.cs
//
// This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace Web_Config
{
	/// <summary>
	/// Summary description for Web_ConfigTest.
	/// </summary>
	class Web_ConfigTest
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   Web_Config.Web_Config2 doc = Web_Config.Web_Config2.CreateDocument();			
			//   Web_Config.connectionStringsType root = doc.connectionStrings.Append();
			//   ...
			//   doc.SaveToFile("Web_Config1.xml", true);
			//
			// Example code to load and save a structure:
			//   Web_Config.Web_Config2 doc = Web_Config.Web_Config2.LoadFromFile("Web_Config1.xml");
			//   Web_Config.connectionStringsType root = doc.connectionStrings.First;
			//   ...
			//   doc.SaveToFile("Web_Config1.xml", true);

		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("Web_Config Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
